### ISSUE TITLE
no command line interface raise an error

### ISSUE THREAD

**Issue by ragnarok22** [lugodev/ptb-django-cookiecutter#4]
* Repo version used: lastest
* Python version: 3.8
* Operating System: Ubuntu 20.0.4.2

### Description
Creating a project with no command line interface raise an error

### Output

```
Select command_line_interface:
1 - Click
2 - Argparse
3 - No command-line interface
Choose from 1, 2, 3 [1]: 3
create_author_file [y]: 
Select open_source_license:
1 - MIT license
Choose from 1 [1]: 
Traceback (most recent call last):
  File "/tmp/tmpm9jc6wfl.py", line 19, in <module>
    remove_file(cli_file)
  File "/tmp/tmpm9jc6wfl.py", line 8, in remove_file
    os.remove(os.path.join(PROJECT_DIRECTORY, filepath))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ragnarok/Projects/python/telegrambots/apimania_telegram_bot/apimania_telegram_bot/cli.py'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by lugodev** [comment]
@ragnarok22 Thanks for reporting this. Fixing it asap.

**Comment by lugodev** [comment]
@all-contributors add @ragnarok22 in bug, review and test.

**Comment by lugodev** [comment]
@ragnarok22 Fixed, releasing it in the next version, very soon.
